BEGIN;

CREATE TABLE IF NOT EXISTS client_campaign_contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    name VARCHAR(120) NOT NULL DEFAULT '',
    email VARCHAR(254) NOT NULL,
    email_normalized VARCHAR(254) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    marketing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    consent_source VARCHAR(500) NOT NULL DEFAULT '',
    consented_at TIMESTAMP WITHOUT TIME ZONE,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    revocation_source VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_campaign_contact_client_email UNIQUE (client_id, email_normalized)
);
CREATE INDEX IF NOT EXISTS ix_client_campaign_contacts_id ON client_campaign_contacts(id);
CREATE INDEX IF NOT EXISTS ix_client_campaign_contacts_client_id ON client_campaign_contacts(client_id);
CREATE INDEX IF NOT EXISTS ix_client_campaign_contacts_email_normalized ON client_campaign_contacts(email_normalized);

CREATE TABLE IF NOT EXISTS campaign_contact_consent_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id INTEGER NOT NULL REFERENCES client_campaign_contacts(id) ON DELETE RESTRICT,
    event_key VARCHAR(100) NOT NULL UNIQUE,
    event_type VARCHAR(20) NOT NULL CHECK (event_type IN ('opt_in', 'opt_out')),
    email_snapshot VARCHAR(254) NOT NULL,
    source VARCHAR(500) NOT NULL,
    occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_campaign_contact_consent_events_id ON campaign_contact_consent_events(id);
CREATE INDEX IF NOT EXISTS ix_campaign_contact_consent_events_contact_id ON campaign_contact_consent_events(contact_id);

CREATE TABLE IF NOT EXISTS promotion_campaigns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_key VARCHAR(80) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    subject VARCHAR(255) NOT NULL DEFAULT '',
    body TEXT NOT NULL DEFAULT '',
    image_path VARCHAR(500) NOT NULL DEFAULT '',
    image_mime VARCHAR(80) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'generating', 'generation_failed', 'sending', 'sent', 'partial', 'cancelled')),
    revision INTEGER NOT NULL DEFAULT 1,
    confirmed_revision INTEGER,
    confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    generation_error VARCHAR(80) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_promotion_campaigns_id ON promotion_campaigns(id);
CREATE INDEX IF NOT EXISTS ix_promotion_campaigns_request_key ON promotion_campaigns(request_key);
CREATE INDEX IF NOT EXISTS ix_promotion_campaigns_status ON promotion_campaigns(status);

CREATE TABLE IF NOT EXISTS promotion_recipients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id INTEGER NOT NULL REFERENCES promotion_campaigns(id) ON DELETE RESTRICT,
    contact_id INTEGER REFERENCES client_campaign_contacts(id) ON DELETE SET NULL,
    client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    client_name_snapshot VARCHAR(255) NOT NULL,
    contact_name_snapshot VARCHAR(120) NOT NULL DEFAULT '',
    email_snapshot VARCHAR(254) NOT NULL,
    email_normalized VARCHAR(254) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sending', 'sent', 'failed', 'unknown', 'suppressed', 'cancelled')),
    provider_message_id VARCHAR(255) NOT NULL DEFAULT '',
    error_code VARCHAR(80) NOT NULL DEFAULT '',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP WITHOUT TIME ZONE,
    sent_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_promotion_recipient_email UNIQUE (campaign_id, email_normalized)
);
CREATE INDEX IF NOT EXISTS ix_promotion_recipients_id ON promotion_recipients(id);
CREATE INDEX IF NOT EXISTS ix_promotion_recipients_campaign_id ON promotion_recipients(campaign_id);
CREATE INDEX IF NOT EXISTS ix_promotion_recipients_contact_id ON promotion_recipients(contact_id);
CREATE INDEX IF NOT EXISTS ix_promotion_recipients_client_id ON promotion_recipients(client_id);
CREATE INDEX IF NOT EXISTS ix_promotion_recipients_status ON promotion_recipients(status);

CREATE TABLE IF NOT EXISTS promotion_campaign_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id INTEGER NOT NULL REFERENCES promotion_campaigns(id) ON DELETE RESTRICT,
    event_key VARCHAR(100) NOT NULL UNIQUE,
    event_type VARCHAR(40) NOT NULL,
    revision INTEGER NOT NULL,
    details JSON NOT NULL DEFAULT '{}'::json,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_promotion_campaign_events_id ON promotion_campaign_events(id);
CREATE INDEX IF NOT EXISTS ix_promotion_campaign_events_campaign_id ON promotion_campaign_events(campaign_id);

COMMIT;
